// This file is auto-generated by ts_compile() - do not edit manually.
// Source: src/rserve/demo.R

import { Robj } from 'rserve-ts';
import { z } from 'zod';


export const bad_fn = Robj.ocap([], z.union([Robj.numeric(1), Robj.null()]));
export const fn_first = Robj.ocap([z.union([z.string(), z.array(z.string())])], Robj.character(1));
export const fn_mean = Robj.ocap([z.union([z.number(), z.instanceof(Float64Array)])], Robj.numeric(1));
export const iterate = Robj.ocap([Robj.js_function([z.number()], z.number())], Robj.null());
export const sample_num = Robj.ocap([z.instanceof(Float64Array), z.number()], Robj.numeric());


export type TBad_fn = z.infer<typeof bad_fn>;
export type TFn_first = z.infer<typeof fn_first>;
export type TFn_mean = z.infer<typeof fn_mean>;
export type TIterate = z.infer<typeof iterate>;
export type TSample_num = z.infer<typeof sample_num>;


export const demoAppSchema = {
  bad_fn,
  fn_first,
  fn_mean,
  iterate,
  sample_num
} satisfies z.ZodRawShape;

export type TDemoApp = z.infer<z.ZodObject<typeof demoAppSchema, "strip">>;

export default demoAppSchema;
